# action.yml
name: 'cloudflared-service-token-scp-proxy'
description: 'Copy files through cloudflared tunnel proxy, inside github actions'
author: jeremyoverman
branding:
  icon: copy
  color: purple
inputs:
  CLIENT_ID:  # id of input
    description: 'Cloudflare access tunnel, service token id'
    required: true
    default: 'default'
  CLIENT_SECRET:  # id of input
    description: 'Cloudflare access tunnel, service token secret'
    required: true
    default: 'default'
  PUBLIC_KEY:  # id of input
    description: 'Asymmetric ssh keys for the intended client'
    required: true
    default: 'default'
  PRIVATE_KEY:  # id of input
    description: 'Asymmetric ssh keys for the intended client'
    required: true
    default: 'default'
  HOST:  # id of input
    description: 'Cloudflare access tunnel, associated application domain'
    required: true
    default: '0.0.0.0'
  USER:  # id of input
    description: 'Remote target username'
    required: true
    default: 'root'
  PORT:  # id of input
    description: 'Ssh port'
    required: false
    default: '22'
  KEY_TYPE:  # id of input
    description: 'SSH key type, like id_rsa or id_ed25519'
    required: false
    default: 'id_rsa'
  FILES:  # id of input
    description: 'List of files to copy'
    required: true
    default: ''
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.HOST }}
    - ${{ inputs.USER }}
    - ${{ inputs.CLIENT_ID }}
    - ${{ inputs.CLIENT_SECRET }}
    - ${{ inputs.PUBLIC_KEY }}
    - ${{ inputs.PRIVATE_KEY }}
    - ${{ inputs.KEY_TYPE }}
    - ${{ inputs.PORT }}
    - ${{ inputs.FILES }}