name: Generate Action Docs

on: [pull_request]

jobs:
  doc:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: pndurette/gh-actions-auto-docs@v1